### ISSUE TITLE
Thrown error has no information

### ISSUE THREAD

**Issue by binarykitchen** [maxogden/websocket-stream#50]
Test case: Load single-page app, shut down server and try to connect. An error event occurs but it doesn't say anything.

Here the code on the client-side (single-page app):

```
var stream = websocket(...)

stream.on('error', function(err) {
    console.error(err.toString())
})
```

which will print an object blurb like that

```
Event {clipboardData: undefined, path: NodeList[0], cancelBubble: false, returnValue: true, srcElement: WebSocket…}
```

But I expect something like that

```
WebSocket connection to 'wss://localhost:8080/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
```

**Comment by binarykitchen** [comment]
Ping?

**Comment by binarykitchen** [comment]
@maxogden ?

**Comment by maxogden** [comment]
we pass the raw error event from the websocket: https://github.com/maxogden/websocket-stream/blob/b71b1d85a046eb2bb983879e2549d426810bc9c5/stream.js#L67-L69. 

you can add your own `websocket.on('close')` to get more detailed info as per the websocket spec (http://stackoverflow.com/questions/18803971/websocket-onerror-how-to-read-error-description)

**Comment by binarykitchen** [comment]
Oh I see ... thanks!

**Comment by mvayngrib** [comment]
@mcollina i think this is where this issue https://github.com/mqttjs/MQTT.js/issues/623 starts. It would be good to propagate the CloseEvent, rather than the faceless Event from onerror

@maxogden i might be wrong, but isn't onerror always followed by onclose, which has a better error? Can we wait a tick in onerror to see if we get onclose with an error, and destroy using that error instead?

**Comment by mcollina** [comment]
the codebase has changed completely since this, so I very much doubt it.

**Comment by mvayngrib** [comment]
hm, well i don't see the 'close' event propagating an error from here, as the stream is destroyed in onerror. And the MQTT client only pays attention to the error event emitted by 'close'

**Comment by mcollina** [comment]
@mvayngrib can you send a PR to fix it? I'm not understanding what the problem is.

**Comment by mvayngrib** [comment]
@mcollina maybe just take look at a sketch here: https://github.com/maxogden/websocket-stream/compare/master...mvayngrib:closeerror

does that clear things up or the opposite? :)  Unfortunately, this means that test-client.js tests fail, because the closeEvent.wasClean === false when the stream is terminated (as opposed to closed via a WebSocket close handshake)

**Comment by mcollina** [comment]
@mvayngrib how are the test failing? I think you need to add a bit more logic so that only one error get emitted. I think you might be calling `destroy()` twice right now.

**Comment by mvayngrib** [comment]
@mcollina i think both `proxy` and `duplexify` prevent destroy from actually running twice. Anyway, it's the same in the current implementation, I don't think i changed anything in that sense.

the test fails because in test-client.js, when stream.end() / stream.destroy() is called the resulting CloseEvent has wasClean === false, which in my fork ends up emitting an unhandled 'error' event.

**Comment by mvayngrib** [comment]
@mcollina nm, that's my bad, i didn't read the README carefully so i wasn't running the client tests correctly. My closeerror branch seems to pass the tests just fine, so i'll try to add a differentiating test

**Comment by mvayngrib** [comment]
@mcollina added differentiating test https://github.com/maxogden/websocket-stream/pull/125

the MQTT client issue will need to be solved separately. Maybe it can ignore the underlying stream's 'error' events unless they're instances of CloseEvent?
