### ISSUE TITLE
pipe() and closed streams

### ISSUE THREAD

**Issue by fabiosantoscode** [maxogden/websocket-stream#51]
Shouldn't every stream's `.pipe()` method close when the piped stream is closed?

If you clone https://github.com/fabiosantoscode/websocket-stream-issue, run `node server.js`, open a connection with `wscat`, close it, open another `wscat`, and type some data, server.js will crash because pipe is trying to write to a closed socket.

All it's doing is echoing incoming messages to other sockets in a simplistic way.

I might be wrong, but I expect pipe() to not crash my application when the piped-to stream closes.

Am I missing something?

Please excuse me if this issue contains anything offensive or plain wrong. I'm not as sober as I should be while trying to write networking code.

**Comment by 3sv** [comment]
I have the same issues, and also find this strange behaviour. The destroy function of the underlying stream is overwritten by a function that just closes the socket.

I have added "proxy.emit('close')" to the destroy function because this is called normally by the original stream destroy function. 
In the onerror function I have added
if (err)
   self.emit('error', err)
before the destroy call.

In this way the stream is properly closed. When handling the stream.on('close') the close is never fired with the original code when the client just drops the connection. By adding this calls the close is fired properly.


Is this the proper solution to this problem?

**Comment by mafintosh** [comment]
@fabiosantoscode the repo is empty. could you upload the example?

**Comment by fabiosantoscode** [comment]
Oh, my bad.

It's up there now.

**Comment by mcollina** [comment]
This should be fixed in 1.2.0. Please test :). Thank so much for reporting it!
